# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2de2f33a4a9a87e2b3b0e6cde37aa14d66be501846785091b01853a0c4d1d57844a93ea113b42a0e14a0056a141a79174928d50203ca82b0aa567caed35af52b

test:
  secret_key_base: fa764c40f7cfbb4587f018027ec55fb0c03d30e265102f62e032fbb91415d011c32adde6316af6dd5b6aeb4a455d1a7e96dd82c3e9f12205caeb5fb166e16e28

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
